# Configuration variables in array of strings defined in your repository or organization.
config-variables:
  - DASGITHUBAPP_APPID

# Path-specific configurations.
paths:
  # Glob pattern relative to the repository root for matching files. The path separator is always '/'.
  # This example configures any YAML file under the '.github/workflows/' directory.
  .github/workflows/**/*.{yml,yaml}:
    # List of regular expressions to filter errors by the error messages.
    ignore:
      # Ignore the specific error from shellcheck
      - 'shellcheck reported issue in this script: SC2086:.+' # double quote to prevent globbing and word splitting
      - 'shellcheck reported issue in this script: SC2129:.+' # Consider using { cmd1; cmd2; } >> file instead of individual redirects.