enum ColumnDefinition {
  kilometre,
  time,
  route,
  trackEquipment,
  icons1,
  bracketStation,
  informationCell,
  icons2,
  icons3,
  localSpeed,
  brakedWeightSpeed,
  advisedSpeed,
  communicationNetwork,
  gradientUphill,
  gradientDownhill,
}
