package ch.sbb.das.backend.features.internal;

public enum RuFeatureKey {
    WARNAPP,
    CUSTOMER_ORIENTED_DEPARTURE_PROCESS,
    CHECKLIST_DEPARTURE_PROCESS,
    DISPLAY_PLANNED_TIME_DEVIATION,
    DISPLAY_BRAKE_LOAD_SLIP_BRAKE_DETAILS,
}
