enum OrderPriority {
  shuntingMovementStart,
  cabSignalingStart,
  group,
  balise,
  trainDriverTurnoverStart,
  servicePoint,
  signal,
  baseData,
  operationalIndication,
  trainDriverTurnoverEnd,
  lineFootNotes,
  opFootNote,
  curve,
  trackFootNote,
  cabSignalingEnd,
  shuntingMovementEnd,
}
