name: Report Finding
description: Findings aus dem Fachtesting oder produktiven Gebrauch ans DAS Team melden.
labels: ["finding"]
projects: ["SchweizerischeBundesbahnen/10"]
assignees:
  - marcdettwiler
  - StephanieFrancke
body:
  - type: markdown
    attributes:
      value: |
        Weitere Informationen zum Ausfüllen eines Findings findest du unter [Guideline für die Erfassung von Findings](https://confluence.sbb.ch/x/a4l4sw).
  - type: textarea
    attributes:
      label: Beschreibung
      description: Beschreibung vom Finding
    validations:
      required: true
  - type: textarea
    attributes:
      label: Schritte zum Finding
      description: Was wurde gemacht, um das Finding zu verursachen? Falls vorhanden, bitte Printscreens einfügen.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Erwartetes Verhalten
      description: Was wäre das korrekte/erwartete Verhalten gewesen?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Betriebssystem
      description: Welches Betriebsystem wurde genutzt? Die Version kann über die Systemeinstellungen unter "Info" geprüft werden.
      options:
        - iOS Version 18
        - iOS Version 17
        - Android Version 16
        - Android Version 15
        - Android Version 14
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: DAS Version
      description: Welche Version von DAS wurde genutzt?
      options:
        - 0.18.0
        - 0.16.0
        - 0.13.0
        - 0.10.1
        - 0.8.0
        - 0.7.0
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Weitere Anmerkungen
