ALTER TABLE IF EXISTS company
    ADD COLUMN IF NOT EXISTS last_modified_at TIMESTAMP NOT NULL DEFAULT '2026-01-01 00:00:00.000000';

ALTER TABLE IF EXISTS company
    ADD COLUMN IF NOT EXISTS last_modified_by TEXT NOT NULL DEFAULT 'das@sbb.ch';
