management:
  endpoint:
    health:
      probes:
        enabled: true


spring:
  profiles:
    active: ${STAGE:local}
  cloud:
    function:
      definition: boardToGround
    stream:
      bindings:
        boardToGround-out-0:
          destination: default
      solace:
        bindings:
          boardToGround-in-0:
            consumer:
              queue-additional-subscriptions: 90940/2/B2G/*/*/*
      binders:
        solace:
          type: solace
          environment:
            solace:
              java:
                host: ${SOLACE_HOST}
                msgVpn: ${SOLACE_VPN}
                api-properties:
                  AUTHENTICATION_SCHEME: AUTHENTICATION_SCHEME_CLIENT_CERTIFICATE
                  SSL_KEY_STORE: ${SOLACE_KEY_STORE_PATH}
                  SSL_KEY_STORE_FORMAT: JKS
                  SSL_KEY_STORE_PASSWORD: ${SOLACE_KEY_STORE_PASSWORD}
      default-binder: solace
