spring:
  docker:
    compose:
      file: ./das_backend/compose.yaml
  config:
    import: optional:file:./das_backend/.env[.properties]
formation:
  clean-up:
    cron: '-'
  kafka:
    # disable kafka per default
    enabled: false
preload:
  kafka:
    # disable kafka per default
    enabled: false
    timetablePeriodTopic: nets-p.timetable
    timetableTrainTopic: fps.prod.infra.zug
  trainCleanUp:
    cronExpression: "0 0 0 * * *"
    days: 2
  storageCleanUp:
    hours: 24
