spring:
  config:
    import:
      - vault://
  cloud:
    vault:
      authentication: token
      uri: https://vault-nonprod.sbb.ch

  datasource:
    url: jdbc:postgresql://localhost:5432/driver_advisory_system
    username: myuser
    password: secret
endpoints:
  web:
    cors:
      allowed-origins: http://localhost:4200
formation:
  clean-up:
    cron: '-'
  kafka:
    # for local development only
    group-id: ${FORMATION_KAFKA_GROUP_ID_PREFIX}.${USER}
    # disable kafka per default
    enabled: false
trainjourneyplan:
  kafka:
    # for local development only
    group-id: ${PRELOAD_KAFKA_GROUP_ID_PREFIX}.${USER}
    # disable kafka per default
    enabled: false
    timetable-period-topic: nets-p.timetable
    timetable-train-topic: fps.prod.infra.zug
  train-clean-up:
    cron-expression: "0 0 0 * * *"
    days: 2

trainjourneypreloader:
  # adapt corresponding lockAtLeastFor time in @SchedulerLock
  fetch-cron: "0 */5 * * * *"
  storage-clean-up:
    hours: 24

preload:
  bucket:
    accessKey:
    secretKey:

proxy:
  basic-auth: username:password

sfera:
  topic-prefix:
