server:
  port: 8081

application:
  topic:
    sfera-custom-prefix: ${USER}/

spring:
  config:
    import: vault://
  cloud:
    vault:
      authentication: token
      uri: https://vault-nonprod.sbb.ch
    stream:
      binders:
        solace:
          environment:
            solace:
              java:
                host: ${SOLACE_HOST}
                msgVpn: ${SOLACE_VPN}
                api-properties:
                  SSL_KEY_STORE: classpath:user_certificate.p12
                  SSL_KEY_STORE_PASSWORD: ${SOLACE_KEY_STORE_PASSWORD}

localregulations.path: classpath:localregulations.json

management:
  endpoints:
    web:
      cors:
        allowed-origins: http://localhost:4200

db:
  url: jdbc:postgresql://localhost:5432/driver_advisory_system
  user: myuser
  password: secret