class const AbfahrtDetectionAlgorithmusProperties({
  required final double berechnungsZeit,
  required final int lengthForInitialization,
  required final int slowWindowLength,
  required final int fastWindowLength,

  // Algo3
  required final int haltDelayCount,
  required final double maxDistance,

  // Algo5
  required final int integratorWindowLength,
  required final double hystereseAbfahrt,
  required final double hystereseHalt,
  required final double hystereseHandbewegungPositiv,
  required final double hystereseHandbewegungNegativ,
  required final int hystereseHandbewegungAnzahlNegativ,
  required final int handbewegungWindowLength,

  // Algo7
  required final int peakDetectorWindowLength,
  required final int peakDetectorBorderLength,
  required final double peakDetectorDifferenzMittelwert,
  required final double peakDetectorSchwelle,
  required final double peakDetectorSchwelleBorder,
  required final int peakDetectorDelay,

  required final int abfahrtDetektorLength,
  required final int abfahrtDetektorLaengeHalt,
  required final double abfahrtDetektorSchwelleFahrt,
  required final double abfahrtDetektorSchwelleQuiet,

  required final int haltDetektorLength,
  required final int haltDetektorLaengeHalt,
  required final double haltDetektorSchwelleHalt,
  required final double haltDetektorSchwelleQuiet,

  required final int ruheDetektionLangAnzahlPositiv,
  required final double ruheDetektionLangSchwellePositiv,
  required final int ruheDetektionLangAnzahlNegativ,
  required final double ruheDetektionLangSchwelleNegativ,

  required final int ruheDetektionKurzAnzahlPositiv,
  required final double ruheDetektionKurzSchwellePositiv,
  required final int ruheDetektionKurzAnzahlNegativ,
  required final double ruheDetektionKurzSchwelleNegativ,

  // Algo11
  required final int slowIntegratorWindowLength,
  required final int slowAbfahrtDetektorLength,
  required final int slowAbfahrtDetektorLaengeHalt,
  required final double slowAbfahrtDetektorSchwelleFahrt,
  required final double slowAbfahrtDetektorSchwelleQuiet,

  required final int gravitationIntegratorWindowLength,
  required final int gravitationHystereseRotationAnzahlPositiv,
  required final double gravitationHystereseRotationSchwellePositiv,
  required final int gravitationHystereseRotationAnzahlNegativ,
  required final double gravitationHystereseRotationSchwelleNegativ,
  required final int gravitationAbfahrtDetektorLength,
  required final int gravitationAbfahrtDetektorLaengeHalt,
  required final double gravitationAbfahrtDetektorSchwelleFahrt,
  required final double gravitationAbfahrtDetektorSchwelleQuiet,
  required final int gravitationHaltDetektorLength,
  required final int gravitationHaltDetektorLaengeHalt,
  required final double gravitationHaltDetektorSchwelleHalt,
  required final double gravitationHaltDetektorSchwelleQuiet,

  required final double hystereseHandbewegung2Positiv,
  required final double hystereseHandbewegung2Negativ,
  required final int hystereseHandbewegung2AnzahlNegativ,
  required final int touchDelay,

  // Algo12
  required final int hystereseFahrtDeltaLength,
  required final double hystereseFahrtDeltaSchwelle,
  required final int hystereseFahrtDeltaAnzahlUeberSchwelle,

  // Algo13
  required final double hystereseFahrtLocationSchwelleSpeed,
  required final int hystereseFahrtLocationGueltigkeitsDauer,

  // Algo14
  required final int lageaenderungWindowLength,
  required final double lageaenderungSchwelle,
  required final int lageaenderungDelay,
  required final int lageaenderungOrNachAnd,

  // Algo15
  required final int speedNormalizerGueltigkeitsDauer,

  required final int locationAbfahrtDetektorLength,
  required final int locationAbfahrtDetektorLaengeHalt,
  required final double locationAbfahrtDetektorSchwelleFahrt,

  required final int slowLocationAbfahrtDetektorLength,
  required final int slowLocationAbfahrtDetektorLaengeHalt,
  required final double slowLocationAbfahrtDetektorSchwelleFahrt,

  required final int locationHaltDetektorLength,
  required final double locationHaltDetektorSchwelleMin,
  required final double locationHaltDetektorSchwelleMax,
  required final int minimaleAnzahlZwischenZweiAbfahrten,
}) {
  factory AbfahrtDetectionAlgorithmusProperties.defaultProperties() {
    return AbfahrtDetectionAlgorithmusProperties(
      berechnungsZeit: 2,
      lengthForInitialization: 500,
      slowWindowLength: 500,
      fastWindowLength: 100,
      haltDelayCount: 500,
      maxDistance: 0.005,
      integratorWindowLength: 250,
      hystereseAbfahrt: 1.75,
      hystereseHalt: 0.55,
      hystereseHandbewegungPositiv: 0.5,
      hystereseHandbewegungNegativ: 0.1,
      hystereseHandbewegungAnzahlNegativ: 25,
      handbewegungWindowLength: 25,
      peakDetectorWindowLength: 100,
      peakDetectorBorderLength: 25,
      peakDetectorDifferenzMittelwert: 0.008,
      peakDetectorSchwelle: 0.1,
      peakDetectorSchwelleBorder: 0.05,
      peakDetectorDelay: 25,
      abfahrtDetektorLength: 500,
      abfahrtDetektorLaengeHalt: 250,
      abfahrtDetektorSchwelleFahrt: 0.03,
      abfahrtDetektorSchwelleQuiet: 0.002,
      haltDetektorLength: 500,
      haltDetektorLaengeHalt: 250,
      haltDetektorSchwelleHalt: -0.04,
      haltDetektorSchwelleQuiet: 0.002,
      ruheDetektionLangAnzahlPositiv: 0,
      ruheDetektionLangSchwellePositiv: 0.0025,
      ruheDetektionLangAnzahlNegativ: 1250,
      ruheDetektionLangSchwelleNegativ: 0.0025,
      ruheDetektionKurzAnzahlPositiv: 0,
      ruheDetektionKurzSchwellePositiv: 0.0015,
      ruheDetektionKurzAnzahlNegativ: 500,
      ruheDetektionKurzSchwelleNegativ: 0.0015,
      slowIntegratorWindowLength: 1000,
      slowAbfahrtDetektorLength: 1500,
      slowAbfahrtDetektorLaengeHalt: 1000,
      slowAbfahrtDetektorSchwelleFahrt: 3.5,
      slowAbfahrtDetektorSchwelleQuiet: 0.1,
      gravitationIntegratorWindowLength: 250,
      gravitationHystereseRotationAnzahlPositiv: 0,
      gravitationHystereseRotationSchwellePositiv: 1.25,
      gravitationHystereseRotationAnzahlNegativ: 25,
      gravitationHystereseRotationSchwelleNegativ: 0.1,
      gravitationAbfahrtDetektorLength: 500,
      gravitationAbfahrtDetektorLaengeHalt: 250,
      gravitationAbfahrtDetektorSchwelleFahrt: 999,
      gravitationAbfahrtDetektorSchwelleQuiet: 0.0025,
      gravitationHaltDetektorLength: 500,
      gravitationHaltDetektorLaengeHalt: 250,
      gravitationHaltDetektorSchwelleHalt: -0.04,
      gravitationHaltDetektorSchwelleQuiet: 0.0025,
      hystereseHandbewegung2Positiv: 1.25,
      hystereseHandbewegung2Negativ: 0.1,
      hystereseHandbewegung2AnzahlNegativ: 250,
      touchDelay: 100,
      hystereseFahrtDeltaLength: 3000,
      hystereseFahrtDeltaSchwelle: 0.002,
      hystereseFahrtDeltaAnzahlUeberSchwelle: 2000,
      hystereseFahrtLocationGueltigkeitsDauer: 100,
      hystereseFahrtLocationSchwelleSpeed: 3.0,
      lageaenderungWindowLength: 5,
      lageaenderungSchwelle: 0.2,
      lageaenderungDelay: 100,
      lageaenderungOrNachAnd: 2,
      speedNormalizerGueltigkeitsDauer: 150,
      locationAbfahrtDetektorLength: 500,
      locationAbfahrtDetektorLaengeHalt: 250,
      locationAbfahrtDetektorSchwelleFahrt: 2.0,
      slowLocationAbfahrtDetektorLength: 1000,
      slowLocationAbfahrtDetektorLaengeHalt: 250,
      slowLocationAbfahrtDetektorSchwelleFahrt: 200,
      locationHaltDetektorLength: 500,
      locationHaltDetektorSchwelleMin: 0.01,
      locationHaltDetektorSchwelleMax: 2.0,
      minimaleAnzahlZwischenZweiAbfahrten: 750,
    );
  }
}
