name: sfera
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  # workspaces
  mqtt: 1.0.0
  http_x: 1.0.0
  logger: 1.0.0

  # https://pub.dev/packages/logging
  logging: ^1.3.0
  # https://pub.dev/packages/collection
  collection: ^1.19.1
  # https://pub.dev/packages/rxdart
  rxdart: ^0.28.0
  # https://pub.dev/packages/xml
  xml: ^6.5.0
  # https://pub.dev/packages/uuid
  uuid: ^4.5.1
  # https://pub.dev/packages/iso_duration
  iso_duration: ^0.1.1
  # https://pub.dev/packages/drift
  drift: ^2.27.0
  # https://pub.dev/packages/drift_flutter
  drift_flutter: ^0.2.4
  # https://pub.dev/packages/path_provider
  path_provider: ^2.1.5
  # https://pub.dev/packages/intl
  intl: ^0.20.2
  # https://pub.dev/packages/meta
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/mockito
  mockito: ^5.4.6
  # https://pub.dev/packages/build_runner
  build_runner: ^2.5.4
  # https://pub.dev/packages/drift_dev
  drift_dev: ^2.27.0
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^6.0.0
