/// Flutter icons DasIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DasIcons
///      fonts:
///       - asset: fonts/DasIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DasIcons {
  DasIcons._();

  static const _kFontFam = 'DasIcons';
  static const String? _kFontPkg = null;

  static const IconData app_icon_warnfunktion_rangier = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
