@import XCTest;
@import integration_test;

// Generated by app/scripts/generate_runner_tests.mjs.
//
// This file creates one XCTest case per Flutter integration test found under
// app/integration_test/test. The Flutter test suite is executed lazily once and
// stores successful test selector names in RunnerSuccessfulTests.
// Each generated XCTest validates that its selector name appears in that list.
//
// The original motivation is to avoid the Xcode 15+ construction watchdog while
// still exposing individual XCTest results instead of a single aggregate test.
static NSMutableArray<NSString *> *RunnerTestFailures;
static NSMutableSet<NSString *> *RunnerSuccessfulTests;
static BOOL RunnerIntegrationTestsDidRun = NO;

@interface RunnerTests : XCTestCase
+ (NSArray<NSString *> *)recordedFailures;
+ (NSArray<NSString *> *)recordedSuccessfulTests;
@end

@implementation RunnerTests

+ (NSArray<NSString *> *)recordedFailures {
  return RunnerTestFailures.copy ?: @[];
}

+ (NSArray<NSString *> *)recordedSuccessfulTests {
  return RunnerSuccessfulTests.allObjects ?: @[];
}

- (void)ensureIntegrationTestsExecuted {
  @synchronized([RunnerTests class]) {
    if (RunnerIntegrationTestsDidRun) {
      return;
    }

    RunnerIntegrationTestsDidRun = YES;
    RunnerTestFailures = [[NSMutableArray alloc] init];
    RunnerSuccessfulTests = [[NSMutableSet alloc] init];

    FLTIntegrationTestRunner *integrationTestRunner = [[FLTIntegrationTestRunner alloc] init];
    [integrationTestRunner testIntegrationTestWithResults:^(SEL testSelector, BOOL success, NSString *failureMessage) {
      NSString *name = NSStringFromSelector(testSelector);
      if (success) {
        [RunnerSuccessfulTests addObject:name];
      } else {
        [RunnerTestFailures addObject:[NSString stringWithFormat:@"%@: %@", name, failureMessage ?: @"(no message)"]];
      }
    }];
  }
}

- (NSString *)recordedFailureWithPrefix:(NSString *)testNamePrefix {
  [self ensureIntegrationTestsExecuted];

  NSString *expectedPrefix = [NSString stringWithFormat:@"%@:", testNamePrefix.lowercaseString];
  for (NSString *failure in RunnerTestFailures ?: @[]) {
    if ([failure.lowercaseString hasPrefix:expectedPrefix]) {
      return failure;
    }
  }

  return nil;
}

- (BOOL)hasRecordedSuccessWithPrefix:(NSString *)testNamePrefix {
  [self ensureIntegrationTestsExecuted];

  for (NSString *successfulTestName in RunnerSuccessfulTests ?: [NSSet set]) {
    if ([successfulTestName.lowercaseString hasPrefix:testNamePrefix.lowercaseString]) {
      return YES;
    }
  }

  return NO;
}

- (void)assertRecordedSuccessWithPrefix:(NSString *)testNamePrefix {
  if ([self hasRecordedSuccessWithPrefix:testNamePrefix]) {
    return;
  }

  NSString *failure = [self recordedFailureWithPrefix:testNamePrefix];
  if (failure != nil) {
    XCTFail(@"%@", failure);
    return;
  }

  NSArray<NSString *> *successfulTests = [[RunnerSuccessfulTests allObjects] sortedArrayUsingSelector:@selector(compare:)];
  XCTFail(@"Expected %@ in successful tests list, but it was not recorded. Successful tests:\n%@",
          testNamePrefix,
          [successfulTests componentsJoinedByString:@"\n"]);
}

// BEGIN GENERATED XCTESTS
// integration_test/test/additional_speed_restriction_modal_test.dart
- (void)testAsrModalWhenModalOpenedThenHidesTimeColumnP7ydFbghPvgMoyaSfNjFTests1219 {
}

// integration_test/test/additional_speed_restriction_modal_test.dart
- (void)testAsrModalWhenMissingOptionalFieldsThenShowsDashesDJrbXirX37Dq6cvL1nLxTests567 {
}

// integration_test/test/additional_speed_restriction_modal_test.dart
- (void)testAsrModalWhenAllDetailsPresentThenShowsAllDetails0eQJ41IWn8ueyne4Nzh2Tests567 {
}

// integration_test/test/additional_speed_restriction_modal_test.dart
- (void)testAsrModalWhenSameRowTappedTwiceThenClosesModalPJoSYPI4xQRZFe8UsGTdTests1875 {
}

// integration_test/test/additional_speed_restriction_modal_test.dart
- (void)testAsrModalWhenRadioChannelTappedWhileOpenThenSwitchesWithoutClosingFYCL15anxOtsmYgvuzl3Tests1875 {
}

// integration_test/test/additional_speed_restriction_modal_test.dart
- (void)testAsrModalWhenNonInteractiveAreaTappedThenClosesModalJajHl07W13dG4g0wsctjTests1875 {
}

// integration_test/test/additional_speed_restriction_modal_test.dart
- (void)testAsrModalWhenComplexAsrWithMultipleEntriesThenShowsAllEntries4dhyrq0I6dm7WCcmpMDRTests227 {
}

// integration_test/test/app_expiration_test.dart
- (void)testAppExpirationWhenExpiresSoonThenShowsDismissibleDialogOnceWdTKidFSmgo3zr9DWxHHTests245 {
}

// integration_test/test/app_expiration_test.dart
- (void)testAppExpirationWhenExpiredThenShowsNonDismissibleDialogRppcazq2UO5W3xR0IZLGTests245 {
}

// integration_test/test/app_link_test.dart
- (void)testAppLinkWhenLinkWithSingleTrainOpensJourneyN2DspgYQ3KU5M4zWXh7QTests97 {
}

// integration_test/test/app_link_test.dart
- (void)testAppLinkWhenLinkWithMultipleTrainsOpensFirstJourneyAndRestInNavigationFvyLq39APcu9HXYDxOReTests97 {
}

// integration_test/test/app_link_test.dart
- (void)testAppLinkWhenLinkWithValidAndUnknownTrainOpensFirstJourneyAndShowsErrorPageForSecondPekbdz3nHeeVcICqD6wYTests97 {
}

// integration_test/test/app_link_test.dart
- (void)testAppLinkWhenLinkWhileUnauthenticatedOpensJourneyAfterLoginFlowAZdIaGI51vKrPz2ShZnRTests97 {
}

// integration_test/test/app_link_test.dart
- (void)testAppLinkWhenLinkWithUnknownTrainShowsErrorPage15g1jT1sZm8j2GSw3mbsTests97 {
}

// integration_test/test/app_link_test.dart
- (void)testAppLinkWhenLinkWithTafTapStartAndEndShowsTrainDriverTurnoverRowsTLIAIKurErFTRsyXwV1STests296 {
}

// integration_test/test/app_link_test.dart
- (void)testAppLinkWhenLinkWithReturnUrlShouldUseReturnUrlOverDefaultTourSystemUrlB6vkX9lfHGRkIzsZ1us6Tests9796 {
}

// integration_test/test/app_link_test.dart
- (void)testAppLinkWhenAlreadyOnJourneyPageReceivingDeeplinkOpensNewJourneyRWOQbfY4K3XnuDZ0sdXOTests1852 {
}

// integration_test/test/app_link_test.dart
- (void)testAppLinkWhenLinkWithSingleTrainShowsCompanyMatchSelectionWRCsXpxpYvtJofkQoFYNTests702 {
}

// integration_test/test/app_link_test.dart
- (void)testAppLinkWhenAlreadyOnJourneyPageReceivingDeeplinkOpensSelectionWithCompanyMatchMSFNFsBOiBB94sxZptbDTests702 {
}

// integration_test/test/app_link_test.dart
- (void)testAppLinkWhenAlreadyOnJourneyPageReceivingDeeplinkOpensNewJourneyWithMatchingRu3rMlQu5RKMLbWnkW3HAtTests702 {
}

// integration_test/test/automatic_advancement_test.dart
- (void)testAutomaticAdvancementWhenJourneyLoadedThenScrollsAutomaticallyZGzAbCSbv7PPJgvNDu2MTests94 {
}

// integration_test/test/automatic_advancement_test.dart
- (void)testAutomaticAdvancementWhenIdleTimeReachedThenScrollsBackToPosition78V0rplxI8A6LGzwHf3RTests94 {
}

// integration_test/test/automatic_advancement_test.dart
- (void)testAutomaticAdvancementWhenTableIsTappedThenIdleTimeIsNotResetO2JzoXIvpJXPp5KP71BtTests1923 {
}

// integration_test/test/automatic_advancement_test.dart
- (void)testAutomaticAdvancementWhenTableIsScrolledThenIdleTimeIsResetCwg37CLdZA4TygXWeEUsTests192394 {
}

// integration_test/test/automatic_advancement_test.dart
- (void)testAutomaticAdvancementWhenReEnabledThenScrollsToCurrentPosition4Ia2ip74kN6FpYMEnx80Tests94 {
}

// integration_test/test/automatic_advancement_test.dart
- (void)testAutomaticAdvancementWhenDisabledThenDoesNotScroll4JEbtNRJ2FHdV4Ab1fx9Tests94 {
}

// integration_test/test/automatic_advancement_test.dart
- (void)testAutomaticAdvancementWhenJourneyLoadedThenIsEnabledByDefaultQOLT57vft3usf96YbYjATests94 {
}

// integration_test/test/automatic_advancement_test.dart
- (void)testAutomaticAdvancementWhenDisabledThenShowsStickyFooter2UNRYR5awQHQMmyn9QaeTests94 {
}

// integration_test/test/automatic_advancement_test.dart
- (void)testTimedAdvancementWhenJourneyLoadedThenAdvancesCorrectly6VsC8w1YfGUW4CkTbX7QTests1419 {
}

// integration_test/test/automatic_advancement_test.dart
- (void)testTimedAdvancementWhenJourneyLoadedThenAdvancesByOperationalAndPlannedTimesKp3WqzT9rLxYhNv2QmDeTests939 {
}

// integration_test/test/automatic_advancement_test.dart
- (void)testTimedAdvancementWhenSignaledPositionBehindAndPunctualityHiddenThenSignalWinsXw7RtLm2QpKvYc9HbNd3Tests2491 {
}

// integration_test/test/brake_load_slip_test.dart
- (void)testBrakeSlipWhenPositionUpdateWhileBrakeSlipPageOpenThenDoesNotUpdateToNewPositionLqq9jBQeZXKwYjM3vWYFTests1605 {
}

// integration_test/test/brake_load_slip_test.dart
- (void)testBrakeSlipWhenNoDataAvailableThenDoesNotShowButton4z9DtXCNPqahGoefcXqOTests692568 {
}

// integration_test/test/brake_load_slip_test.dart
- (void)testBrakeSlipWhenFormationDataLoadedThenShowsInformationAndNavigationLTuJGUbeVyBkXBp0mWCSTests692 {
}

// integration_test/test/brake_load_slip_test.dart
- (void)testBrakeSlipWhenSpecialIndicatorsArePresentThenShowsBannersYgF4hHe8Cl7C98NaC5xjTests692 {
}

// integration_test/test/brake_load_slip_test.dart
- (void)testBrakeSlipWhenDifferentBrakeSeriesInFormationThenShowsNotificationNFIIta4nBxJ20VkGCgH0Tests692 {
}

// integration_test/test/brake_load_slip_test.dart
- (void)testBrakeSlipModalWhenOpenedThenDisplaysCorrectInformationLxpggIMjzbU9W3aoNNeWTests692568 {
}

// integration_test/test/brake_load_slip_test.dart
- (void)testBrakeSlipModalWhenIdleTimeoutElapsesThenNeverClosesAutomatically1g0A50LfMqOsfFqkWrkJTests1867 {
}

// integration_test/test/brake_load_slip_test.dart
- (void)testBrakeSlipModalWhenButtonTappedWhileOpenThenClosesModal7VngjKboIfqc2qmsEuwsTests1875 {
}

// integration_test/test/brake_load_slip_test.dart
- (void)testBrakeSlipModalWhenNonInteractiveAreaTappedThenClosesModal4u1bk9VV17S4h9RpUQxmTests1875 {
}

// integration_test/test/brake_load_slip_test.dart
- (void)testBrakeSlipModalWhenFullscreenButtonTappedThenOpensFullscreenSLTLSnINc1xWV6Sv6gVKTests692 {
}

// integration_test/test/brake_load_slip_test.dart
- (void)testBrakeSlipWhenFormationUpdatedThenShowsNotificationHt9hpOZmHcaTZUyQb4RfTests695 {
}

// integration_test/test/brake_load_slip_test.dart
- (void)testBrakeSlipWhenFormationRunChangedThenUpdatesRunChangeDisplayIG1dyvhq8hUk2uhyOMOJTests694 {
}

// integration_test/test/brake_load_slip_test.dart
- (void)testBrakeSlipWhenTransportDocumentsAreConfiguredThenButtonVisibilityAndLaunchBehaviorMatchFormationDataK2dX0Vd8r1sZ9fQm7uJmTests1620 {
}

// integration_test/test/chronograph_test.dart
- (void)testChronographWhenNoUpdatesThenHidesPunctualityDisplayRHuNlE41ENvoE7vZK3UpTests300 {
}

// integration_test/test/chronograph_test.dart
- (void)testChronographWhenNoUpdatesThenPunctualityBecomesStale1W4NytAMRiJrry9NzJJ0Tests300 {
}

// integration_test/test/chronograph_test.dart
- (void)testChronographWhenPunctualityUpdateReceivedThenDisplaysCorrectlyCA2h5q5rFvVIvZjoCL9iTests300 {
}

// integration_test/test/chronograph_test.dart
- (void)testChronographWhenNoCalculatedSpeedAndNoPlannedTimesThenHidesPunctuality8bo2dGfbGlmQVHT7mRlBTests19692257 {
}

// integration_test/test/chronograph_test.dart
- (void)testChronographWhenNoSferaDelayAvailableThenShowsPlannedTimeDeviationIXKTMP5ojTtZd7Eo7VF5Tests1851 {
}

// integration_test/test/chronograph_test.dart
- (void)testChronographWhenPlannedTimeDeviationFeatureDisabledThenNeverShowsDeviationIk64KpZ9j4qN3klSOCkBTests1851 {
}

// integration_test/test/chronograph_test.dart
- (void)testChronographWhenJourneyLoadedThenShowsCorrectCurrentTimeXVdCWlyYq41HhAr9p2hmTests79 {
}

// integration_test/test/departure_process_test.dart
- (void)testDepartureProcessWhenFeatureEnabledThenChecklistButtonDisplayedCorrectlyNW7qkKijklYmLt0yngJ6Tests627 {
}

// integration_test/test/departure_process_test.dart
- (void)testDepartureProcessWhenNoCustomerOrientedDepartureThenChecklistButtonOpensDepartureDialogLwlj8frlqY7pBq76LGKuTests627 {
}

// integration_test/test/departure_process_test.dart
- (void)testDepartureProcessWhenFeatureEnabledThenShowsChronographWarningNqR5G6rO4Aw4aeZLyZL4Tests627 {
}

// integration_test/test/external_links_test.dart
- (void)testExternalLinksWhenNoRuSelectedThenShowsEmptyStateYWizuavbVmWzQn5OoqIETests147 {
}

// integration_test/test/external_links_test.dart
- (void)testExternalLinksWhenRuSelectedInProfileThenShowsLinksVNfgpqG3Ma8VUpXenmkYTests147 {
}

// integration_test/test/external_links_test.dart
- (void)testExternalLinksWhenRuSelectionChangesThenUpdatesLinksMzF1gipYtU39GeQHCZcATests147 {
}

// integration_test/test/journey_customer_oriented_departure_test.dart
- (void)testCustomerOrientedDepartureWhenStatusChangesThenDisplaysNotificationsCorrectlyDIW8ooYfMKINdzpGCp4STests148 {
}

// integration_test/test/journey_customer_oriented_departure_test.dart
- (void)testCustomerOrientedDepartureWhenJourneyChangesThenSubscriptionUpdates7cmV7s3vxPmsKqjVUcXDTests148 {
}

// integration_test/test/journey_header_test.dart
- (void)testJourneyHeaderWhenConnectivityChangesThenShowsCorrectStateINnxRgqXwEq3DKjj5xkoTests119 {
}

// integration_test/test/journey_header_test.dart
- (void)testJourneyHeaderWhenJourneyLoadedThenTurnsOnAlwaysOnDisplayWxr40hIhESiOEWYDJTeDTests591 {
}

// integration_test/test/journey_header_test.dart
- (void)testJourneyHeaderWhenJourneyClosedThenTurnsOffAlwaysOnDisplay85sJ2C4mLMJHgOJ8qZCXTests591 {
}

// integration_test/test/journey_header_test.dart
- (void)testJourneyHeaderWhenTrainActiveThenHidesAppBarY8vN9CR9fYwhIrxBzq68Tests79670 {
}

// integration_test/test/journey_header_test.dart
- (void)testJourneyHeaderWhenThemeSwitchTappedThenSwitchesThemeZhLtX4wiqLsmQxd537psTests102 {
}

// integration_test/test/journey_header_test.dart
- (void)testJourneyHeaderWhenExtendedMenuOpenedThenShowsCloseButton3ND51AAMNM7zIQ6jQuJsTests497 {
}

// integration_test/test/journey_header_test.dart
- (void)testJourneyHeaderWhenManeuverModeToggledThenShowsNotificationCnrguVzWD6cZ1wJtRpnmTests242 {
}

// integration_test/test/journey_header_test.dart
- (void)testJourneyHeaderWhenManeuverNotificationSwitchTappedThenHidesNotificationXqiXbNFDNL2YEEEGdMMTTests242 {
}

// integration_test/test/journey_header_test.dart
- (void)testJourneyHeaderWhenWaraAppInstalledAndManeuverModeThenShowsWaraAppLinkMFGC6WM2ZhGAvZOru19zTests242 {
}

// integration_test/test/journey_header_test.dart
- (void)testJourneyHeaderWhenWarnappDisabledThenHidesManeuverModeTWnozeOhBpZvpfl5l5ttTests242445 {
}

// integration_test/test/journey_header_test.dart
- (void)testJourneyHeaderWhenWaraAppInstalledThenShowsOpenMenuItemBC5tOxJbc31r6u4oe66LTests242 {
}

// integration_test/test/journey_header_test.dart
- (void)testJourneyHeaderWhenBatteryAbove15PercentThenHidesIcon5Ehxse0aAny05PMaCF9GTests123 {
}

// integration_test/test/journey_header_test.dart
- (void)testJourneyHeaderWhenBatteryBelow15PercentThenShowsIconAndModalEm5ecUdyqo96tv29cg28Tests123590 {
}

// integration_test/test/journey_header_test.dart
- (void)testJourneyHeaderWhenCommunicationNetworkChangesThenDisplaysCorrectlyC3iKkuijMLoz0xz3gSPtTests125 {
}

// integration_test/test/journey_header_test.dart
- (void)testJourneyHeaderWhenRadioContactsChangeThenDisplaysCorrectlyTr4Sky5hk17bxb622pSTTests125 {
}

// integration_test/test/journey_header_test.dart
- (void)testJourneyHeaderWhenDoubleTappedThenSetsBrightnessToZeroO8gneDOXV3qSXnyNiMPKTests101 {
}

// integration_test/test/journey_header_test.dart
- (void)testJourneyHeaderWhenDraggedRightThenIncreasesBrightnessDsETQyDLocUSGSQfMnmtTests101 {
}

// integration_test/test/journey_header_test.dart
- (void)testJourneyHeaderWhenDraggedLeftThenDecreasesBrightnessVENb2YZWboKuRpbZfdSWTests101 {
}

// integration_test/test/journey_header_test.dart
- (void)testJourneyHeaderWhenDepartureAuthorizationPresentThenDisplaysCorrectly1kg0KDpUjd6nDMn4q7C6Tests226 {
}

// integration_test/test/journey_notification_test.dart
- (void)testNotificationWhenDepartureProcessDialogOpenedThenDisplaysCorrectlyT2Ga4z72ZhW01N8DYa7MTests624627 {
}

// integration_test/test/journey_notification_test.dart
- (void)testNotificationWhenDisturbanceOccursThenShowsAndHidesNotificationM1OE34O4n52uYYiRVMU2Tests244 {
}

// integration_test/test/journey_notification_test.dart
- (void)testNotificationWhenDepartureDispatchReceivedThenDisplaysCorrectlyXgZckSB39KkesylhsvYwTests124 {
}

// integration_test/test/journey_notification_test.dart
- (void)testNotificationWhenMultipleNotificationsThenPrioritizesCorrectlyJ6oFf00OSzO3qQY0XdQmTests1402 {
}

// integration_test/test/journey_notification_test.dart
- (void)testNotificationWhenReauthenticationRequiredThenShowsNotificationJvUwuJ6r5MeLK0dpaaUWTests1320 {
}

// integration_test/test/journey_replacement_series_test.dart
- (void)testReplacementSeriesWhenSuggestedThenSelectsAndReturnsToOriginalMM0ytFua6PYMSusJG4TrTests507 {
}

// integration_test/test/journey_replacement_series_test.dart
- (void)testReplacementSeriesWhenNoReplacementAvailableThenDoesNotSuggestUlgXunAeOxDqNsbksvyiTests507 {
}

// integration_test/test/journey_replacement_series_test.dart
- (void)testReplacementSeriesWhenEndOfSegmentReachedThenMessageDisappearsLIzLPYFFXgBTt95ZmBIRTests507 {
}

// integration_test/test/journey_replacement_series_test.dart
- (void)testReplacementSeriesWhenNoReplacementForBrakeSeriesThenShowsNotificationNVOhVZ4DmLz4SAnArtplTests938 {
}

// integration_test/test/journey_search_overlay_test.dart
- (void)testJourneySearchOverlayWhenOpenedAndDismissedThenTogglesCorrectlyHjtzMqmAjVVBOfkjFxJiTests456 {
}

// integration_test/test/journey_search_overlay_test.dart
- (void)testJourneySearchOverlayWhenOpenedThenShowsDefaultsAndValidation7pJRXknm1Dj2sOExzEtoTests456 {
}

// integration_test/test/journey_search_overlay_test.dart
- (void)testJourneySearchOverlayWhenTrainLoadedThenOpensJourneyWithoutNavigationButtonsPfFjIKgB8Rju5BAkp7S1Tests456 {
}

// integration_test/test/journey_search_overlay_test.dart
- (void)testJourneySearchOverlayWhenMultipleCompanyMatchesThenRedirectsToSelectionScreen78G6WgAFp4dv86tsGl14Tests702 {
}

// integration_test/test/journey_table_additional_speed_restriction_test.dart
- (void)testAdditionalSpeedRestrictionWhenRowDisplayedThenShowsCorrectlyH60HiYVcM6InpQTWSsDiTests87 {
    
}

// integration_test/test/journey_table_additional_speed_restriction_test.dart
- (void)testAdditionalSpeedRestrictionWhenNonAsrRowsBetweenThenColorsCorrectlyYA4sSmXtTNzic4SCKmRCTests87 {
}

// integration_test/test/journey_table_additional_speed_restriction_test.dart
- (void)testAdditionalSpeedRestrictionWhenComplexAsrThenDisplaysCorrectlyPe2ToyhUi8oW7PKpElj7Tests227 {
    [self assertRecordedSuccessWithPrefix:@"testAdditionalSpeedRestrictionWhenComplexAsrThenDisplaysCorrectlyPe2ToyhUi8oW7PKpElj7Tests227"];
}

// integration_test/test/journey_table_additional_speed_restriction_test.dart
- (void)testAdditionalSpeedRestrictionWhenOnEtcsLevel2SectionThenDisplaysCorrectlyX08STS2QuB7Tn1u8HHnYTests120 {
}

// integration_test/test/journey_table_additional_speed_restriction_test.dart
- (void)testAdditionalSpeedRestrictionWhenSequentialAsrThenDisplaysCorrectlyJsCo6tECyuHPKcZMZRxETests566 {
}

// integration_test/test/journey_table_advised_speeds_test.dart
- (void)testAdvisedSpeedWhenNotificationReceivedThenDisplaysCorrectlyDifsm3d1efVsKjn1IJjjTests22812851306 {
}

// integration_test/test/journey_table_advised_speeds_test.dart
- (void)testAdvisedSpeedWhenJourneyLoadedThenDisplaysCorrectly85DIebkYiATNR4kWtS5cTests22812851306 {
}

// integration_test/test/journey_table_balise_level_crossing_test.dart
- (void)testBaliseLevelCrossingWhenMultipleLevelCrossingsThenDisplaysCorrectlyB4vSeswDglqaMsxgpZPETests2241416 {
}

// integration_test/test/journey_table_balise_level_crossing_test.dart
- (void)testBaliseLevelCrossingWhenGroupTappedThenExpandsAndCollapsesAwz0LEkHyRCsE2VMTXprTests2241416454 {
}

// integration_test/test/journey_table_balise_level_crossing_test.dart
- (void)testBaliseLevelCrossingWhenInEtcsLevel2SectionThenDisplaysCorrectlyX6KeDRPFfrKsZlGfYgTMTests14291416224 {
}

// integration_test/test/journey_table_brake_series_test.dart
- (void)testBrakeSeriesWhenDefaultMissingThenShowsQuestionMarksE3YDk2VuPDFkNZxENqh1Tests89 {
}

// integration_test/test/journey_table_brake_series_test.dart
- (void)testBrakeSeriesWhenDefaultFromTrainCharacteristicsThenShowsR1158coWWI2zvgkHncg31PgpTests89 {
}

// integration_test/test/journey_table_brake_series_test.dart
- (void)testBrakeSeriesWhenOpenedThenShowsAllOptions8iPNeVrZhcbzOth6Ao2KTests89 {
}

// integration_test/test/journey_table_brake_series_test.dart
- (void)testBrakeSeriesWhenNoBrakeSeriesDefinedThenShowsMessageNzj1s9oCEioBI3FtabVRTests89 {
}

// integration_test/test/journey_table_calculated_speed_test.dart
- (void)testCalculatedSpeedWhenJourneyLoadedThenDisplaysCorrectlyMfGgJRQKClLfSpfi6maOTests88367 {
}

// integration_test/test/journey_table_calculated_speed_test.dart
- (void)testCalculatedSpeedWhenDisplayedInStickyHeaderThenShowsCorrectlyYx1uKcECluWqDNFyQ6zRTests88367 {
}

// integration_test/test/journey_table_calculated_speed_test.dart
- (void)testCalculatedSpeedWhenNoVproSpeedAtPositionThenHidesPunctualityDlsoheuAER1XBsYUmjNTTests88122 {
}

// integration_test/test/journey_table_calculated_speed_test.dart
- (void)testCalculatedSpeedWhenReducedToLineSpeedThenDisplaysInDifferentColorMk8PekT17HLJlrLqXMz9Tests88367 {
}

// integration_test/test/journey_table_collapsible_rows_test.dart
- (void)testCollapsibleRowsWhenOperationalIndicationDisplayedThenCollapsesIaCfo6CRqrax4porwjuBTests126 {
}

// integration_test/test/journey_table_collapsible_rows_test.dart
- (void)testCollapsibleRowsWhenRadnFootNoteDisplayedThenCollapsesClmYSuxH6dOypT2xgln8Tests625 {
}

// integration_test/test/journey_table_collapsible_rows_test.dart
- (void)testCollapsibleRowsWhenLongTextPresentThenShowsMoreButtonLEGwTOYFxWLauMjiWDDMTests126 {
}

// integration_test/test/journey_table_collapsible_rows_test.dart
- (void)testCollapsibleRowsWhenCombinedIndicationsThenReplacesNewLinesWithDelimiterWn0E9HeXjfz8Lk3XEgvaTests126625 {
}

// integration_test/test/journey_table_collapsible_rows_test.dart
- (void)testCollapsibleRowsWhenSameServicePointThenCombinesIndicationAndFootNotePkZjtPxXkInflC3IIs74Tests126625 {
}

// integration_test/test/journey_table_collapsible_rows_test.dart
- (void)testCollapsibleRowsWhenOperationalIndicationPassedThenCollapsesH9JLGRVgfPYcsgEwWMyXTests126 {
}

// integration_test/test/journey_table_collapsible_rows_test.dart
- (void)testCollapsibleRowsWhenRadnFootNotePassedThenCollapsesSLbIwzyEcCfKwY77CQRzTests625 {
}

// integration_test/test/journey_table_collapsible_rows_test.dart
- (void)testCollapsibleRowsWhenRadnFootNoteDisplayedThenTitleContainsType8XcuHwPmJI1ijGizGFsDTests625 {
}

// integration_test/test/journey_table_collapsible_rows_test.dart
- (void)testSimFootNoteWhenNonSimTrainThenSimFootNoteIsCollapsedGnYPge8jjpnKHq6CbSm1Tests1126 {
}

// integration_test/test/journey_table_collapsible_rows_test.dart
- (void)testSimFootNoteWhenSimTrainThenSimFootNoteIsExpandedAndNotCollapsedWhenPassedWGzkdPjTfFUKkJKNw92kTests1126 {
}

// integration_test/test/journey_table_collapsible_rows_test.dart
- (void)testCollapsibleRowsWhenMovingBackwardsThenResetRowsToDefaultSate60quLbjUFK7kIPulz6LbTests1617 {
}

// integration_test/test/journey_table_station_property_test.dart
- (void)testStationPropertyWhenStationSignsPresentThenDisplaysCorrectly33p6hQftZIHPSWXIQyMFTests127 {
}

// integration_test/test/journey_table_station_property_test.dart
- (void)testStationPropertyWhenPropertiesPresentThenDisplaysCorrectly2048M4EI2XWF3xp9fNzrTests127 {
}

// integration_test/test/journey_table_station_property_test.dart
- (void)testStationPropertyWhenTrainSeriesChangesThenUpdatesDisplay6yG8VYvMt02JOmuS9rDcTests127 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenCurvesPresentThenDisplaysEndOfCurvesCorrectlyGfSq5x3EgvhqDIZFmdAmTests478 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenSummarizedCurveThenDisplaysAsOneFSNNJU7cWww3zx7ZXrfQTests584 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenKilometerAndNetworkChangesThenDisplaysCorrectly4r5G55qZyLCbrPp8bWycTests1251237356 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenGradientPresentThenDisplaysUpAndDownhillWIvYo0q3NNOWuWNkvM28Tests225 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenBrakeSeriesA50ChosenThenFindsTwoCurves6dftwLIxISwNWPYqIBJjTests478584 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenBrakeSeriesR115ChosenThenFindsThreeCurvesGa09YBxY1Saxs4sdpFKqTests478584 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenWhistleAndTramAreaThenDisplaysCorrectlyUsmLmc9mBo7nGo9cREC8Tests224 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenChevronInGroupedItemsThenPositionsCorrectlyJoe81l2AczCXfgNHasnYTests94 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenDefaultBrakeSeriesThenShowsCorrectSpeedValues8X1ka8Bgi8yzoh4UjFZaTests89 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenMissingBrakeSeriesThenShowsCorrectSpeedValuesLLhbvIweHYZFneDKofeeTests89 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenConnectionTrackAndZahnstangePresentThenDisplaysCorrectlyUk1rmjXg0jCGsI5AReThTests136 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenLoadedThenShowsAllColumnsWithHeaders2xKQZqkInzVQYxlvy6h4Tests79 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenRoutePresentThenDisplaysCorrectlyRyZ21eZspmXAa5nGYdJJTests801557 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenProtectionSectionsPresentThenDisplaysCorrectlyHW5ShUks9dJRe4ik706zTests223 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenBothKilometresPresentThenDisplaysBothGXhdMHah4bTjsxlsQHccTests1863 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenBracketStationsThenDisplaysCorrectlyR7bVEtXlOIs8nat7DgNvTests81 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenHaltOnRequestThenDisplaysCorrectlySVXw9sGr7XUI7ZbBeRSZTests81 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenHaltPresentThenDisplaysItalicPsvC3EAHHTI7mNl15VLnTests81 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenServicePointHasTrackGroupThenDisplaysCorrectlyWithDetailModalGObFVFt2aAyPWMXp9cENTests1072 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenCurvesPresentThenDisplaysCurvesCorrectlyPNcLWjDBIMF8IuMwaXueTests82 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenSignalsPresentThenDisplaysCorrectly17wDIW5HykO2IvvtiOBpTests82 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenStationSpeedsThenDisplaysCorrectlyFXMX5vrKhaFEGsmWH1G5Tests82 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenLineSpeedThenAlwaysDisplaysInStickyHeaderJD3NqcaIve8Ivy8cnAWmTests932 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenEtcsLevel2SectionThenHidesLineSpeed3qRWUMgq0aQM4HAXpNjlTests120 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenAdditionalServicePointsThenDisplaysCorrectlyIfROK0ce5yyXlNxw2CzBTests258 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenShuntingMovementThenDisplaysMarkersCorrectly1hJ3sN82MojHdBszhwuDTests264 {
}

// integration_test/test/journey_table_test.dart
- (void)testJourneyTableWhenMultipleColorsThenDisplaysCorrectPriorityBedMotS6Ncw5XayVseo6Tests1125 {
}

// integration_test/test/journey_table_time_test.dart
- (void)testTimeCellWhenFixedPointRelevanceDisplayCorrectIcons3lGb8LE756LixsOVIyG8Tests1201 {
}

// integration_test/test/journey_table_time_test.dart
- (void)testTimeCellWhenFarFutureJourneyThenShowsPlannedTimesOnly8vwuVlLyxynaCMpOv6jxTests84 {
}

// integration_test/test/journey_table_time_test.dart
- (void)testTimeCellWhenNearFutureJourneyThenShowsOperationalAndPlannedTimesNx7aWInXVPGmH5bqoxmGTests84 {
}

// integration_test/test/journey_table_time_test.dart
- (void)testTimeCellWhenManuallySetToPlannedThenAutoSwitchesBackToOperationalZJeVf25WtmGJFcMNAGNFTests84 {
}

// integration_test/test/journey_table_time_test.dart
- (void)testTimeCellWhenDepartureTimeReachedThenUnderlinesTime9EQAkYvdXrJ4e7fZH6AeTests259 {
}

// integration_test/test/journey_table_track_equipment_test.dart
- (void)testTrackEquipmentWhenCabSignalingThenDisplaysCorrectlyDNu1aGjJOxuHG1ka8zHSTests82 {
}

// integration_test/test/journey_table_track_equipment_test.dart
- (void)testTrackEquipmentWhenLoadedThenDisplaysCorrectlyYUBlApq3Bgd4bwgvHGoJTests82 {
}

// integration_test/test/journey_table_track_equipment_test.dart
- (void)testTrackEquipmentWhenSingleTrackNoBlockThenDisplaysCorrectlyUvRMEube4z8gQXU9Zw3bTests230 {
}

// integration_test/test/journey_table_updates_test.dart
- (void)testJourneyUpdatesWhenChangesReceivedThenDisplaysCorrectlyRCW5QKoQdUwtfxVEEIHRTests241 {
}

// integration_test/test/journey_table_updates_test.dart
- (void)testJourneyUpdatesWhenTrainCharacteristicsUpdatedThenIgnoresUpdateLd7g7OsSEKkPbbGjJ5aMTests1416 {
}

// integration_test/test/login_test.dart
- (void)testLoginWhenLogoutDialogIsDismissedThenIsStillLoggedInQRCD5Jy91TVe7KucfsQ7Tests1870 {
}

// integration_test/test/login_test.dart
- (void)testLoginWhenStartedDefaultForIntegrationTestThenIsConnectedToMockBrokerO1tTzfXvce93K82ZFcob {
}

// integration_test/test/login_test.dart
- (void)testLoginWhenLogoutThenDefaultSelectionIsTmsVadOnLoginPageMgPV1riT2X8BFRJXjhSDTests2399 {
}

// integration_test/test/login_test.dart
- (void)testLoginWhenLogoutThenLoginThenWillConnectToTmsVadVeZt1c1nxqKljOKbjk7QTests2399 {
}

// integration_test/test/login_test.dart
- (void)testLoginWhenLogoutThenLoginWithSferaMockToggledThenWillConnectToSferaMockUcMtHMlV4XgL5Dw8BDeOTests2399 {
}

// integration_test/test/manual_advancement_test.dart
- (void)testManualAdvancementWhenServicePointDraggedThenJourneyPositionMovedIU0xYWTQ0mGPaNeRDOU9Tests741 {
}

// integration_test/test/manual_advancement_test.dart
- (void)testManualAdvancementWhenManualPositionSetThenManualModeActivatedUntilJourneyPositionSignaledVF1BuwAJ8oK5QJ9NSrvzTests741 {
}

// integration_test/test/manual_advancement_test.dart
- (void)testManualAdvancementWhenManualPositionSetThenStartTimedAdvancementQidAQQpf9ZctfYvUrotnTests1314 {
}

// integration_test/test/manual_advancement_test.dart
- (void)testManualAdvancementWhenManualPositionSetThenRestartsPositionTimersTvZbKb7A7zMsILORpP0OTests1314 {
}

// integration_test/test/manual_advancement_test.dart
- (void)testManualAdvancementWhenManualPositionSetThenShowsChevronAnimationColorRdLRFyaR0jBcplaGyVb1Tests1617 {
}

// integration_test/test/navigation_test.dart
- (void)testNavigationWhenDrawerOpenedThenShowsNavigationItems4zq12yxOhYBVFfmmbRMuTests80 {
}

// integration_test/test/navigation_test.dart
- (void)testNavigationWhenLinksSelectedThenShowsLinksPage6ud9ZVIyRAaLfwadmi7bTests80 {
}

// integration_test/test/navigation_test.dart
- (void)testNavigationWhenSettingsSelectedThenShowsSettingsPageNSe6ERbY0uoKIFbulzBATests80 {
}

// integration_test/test/navigation_test.dart
- (void)testNavigationWhenProfileSelectedThenShowsProfilePageUwGtLIS6brDbdk4shRWJTests80 {
}

// integration_test/test/navigation_test.dart
- (void)testNavigationWhenTrainJourneySelectedThenShowsFahrtPageF5AHhw7WFEXFVWdrzZH6Tests80 {
}

// integration_test/test/navigation_test.dart
- (void)testNavigationWhenNavigatingBackToJourneyThenJourneyStaysLoadedTVSAOe6GbJ5bWoqPD2v1Tests801557 {
}

// integration_test/test/navigation_test.dart
- (void)testNavigationWhenNavigatingBackThenJourneySettingsNotResetRijOj3T18mvGVZNMrmTqTests80583811 {
}

// integration_test/test/preload_test.dart
- (void)testPreloadWhenStatusChangesThenDisplaysCorrectlyVzryoGxMwq20YJrAmwSNTests90 {
}

// integration_test/test/preload_test.dart
- (void)testPreloadWhenUsingPreloadDataThenReconnectsSuccessfullyNW5bzK5BHRo3TbUA6KWOTests90 {
}

// integration_test/test/profile_test.dart
- (void)testProfileWhenOpenedThenShowsHeaderInformationAsZ1tS4kU7Nf5OXr8iPrTests427 {
}

// integration_test/test/profile_test.dart
- (void)testProfileWhenCompanySelectedThenDisplaysSelectionO7WL0FgVcL2yp91SBkO3Tests427 {
}

// integration_test/test/profile_test.dart
- (void)testProfileWhenTourSystemSelectedThenDisplaysSelectionVg694p8aplw0hptHokayTests427 {
}

// integration_test/test/reduced_journey_table_test.dart
- (void)testReducedJourneyWhenNetworkChangePresentThenDisplaysWithKmBG8f0zcWS1hA8UmHb6XJTests356 {
}

// integration_test/test/reduced_journey_table_test.dart
- (void)testReducedJourneyWhenLoadedThenDisplaysTrainInformationVAiBsV3JAXE2ISLmbuphTests626 {
}

// integration_test/test/reduced_journey_table_test.dart
- (void)testReducedJourneyWhenShuntingMovementJourneyThenDisplaysTrainInformationHrT2S4iEd0EwnEdVvS14Tests264 {
}

// integration_test/test/reduced_journey_table_test.dart
- (void)testReducedJourneyWhenStoppingAndPassingPointsThenDisplaysCorrectly49ntMponGaH3d2TeFrADTests626 {
}

// integration_test/test/reduced_journey_table_test.dart
- (void)testReducedJourneyWhenDuplicatedAsrThenDisplaysOnlyOncePcZSkX79OGMg0q3pQn5DTests626 {
}

// integration_test/test/reduced_journey_table_test.dart
- (void)testReducedJourneyWhenLoadedThenDisplaysPlannedTimesTk4DmRU7XmIasiG1ZnwdTests84 {
}

// integration_test/test/ru_indications_test.dart
- (void)testRuIndicationsWhenShouldReturnMockDataThenIndicationsAreShownYeJd2tuqjOWvKQcf7RYCTests700 {
}

// integration_test/test/ru_indications_test.dart
- (void)testRuIndicationsWhenLongTextWithLinkThenShowMoreIsVisibleGiYge5R7YPQAhT07DGhwTests700 {
}

// integration_test/test/ru_indications_test.dart
- (void)testRuIndicationsWhenLongTextWithMarkdownLinkThenLinkLabelIsRenderedGuPrxy8BQyidLcGugxU0Tests700 {
}

// integration_test/test/ru_indications_test.dart
- (void)testRuIndicationsWhenLongTextExpandedThenFullContentIsVisibleR66dkeS5LMwlWiwhEvsvTests700 {
}

// integration_test/test/service_point_modal_test.dart
- (void)testServicePointModalWhenBahnhofportalLinkTappedThenOpensExpectedUrlHjOshoAnnns1uiZv1piZTests1485 {
}

// integration_test/test/service_point_modal_test.dart
- (void)testServicePointModalWhenOpenedThenHidesKilometreColumnZNZVRPa4v1ZbWe1GLNMITests497 {
}

// integration_test/test/service_point_modal_test.dart
- (void)testServicePointModalWhenInteractedThenOpensAndClosesCorrectlyBULPrI837zbDHbf9ozo1Tests497 {
}

// integration_test/test/service_point_modal_test.dart
- (void)testServicePointModalWhenSameCellTappedTwiceThenClosesModalBlZZhmecRMoz03Ghc4KoTests1875 {
}

// integration_test/test/service_point_modal_test.dart
- (void)testServicePointModalWhenRadioChannelTappedTwiceThenClosesModal47UPdaX6hsiYclucw05KTests1875 {
}

// integration_test/test/service_point_modal_test.dart
- (void)testServicePointModalWhenDifferentServicePointTappedThenSwitchesWithoutClosingYNAh8x76zB856tYRX9MjTests1875 {
}

// integration_test/test/service_point_modal_test.dart
- (void)testServicePointModalWhenActiveTabReselectedThenDoesNothingQD8ziN2IZxVS5DgO9zJdTests1875 {
}

// integration_test/test/service_point_modal_test.dart
- (void)testServicePointModalWhenOpenedThenCollapsesHeaderButtonsQ7V14S34B9g0J5ovsSVYTests497 {
}

// integration_test/test/service_point_modal_test.dart
- (void)testServicePointModalWhenDataAvailableThenShowsOnlyRelevantTabsHCUmXSQ54oN6aACIAwKyTests1040497 {
}

// integration_test/test/service_point_modal_test.dart
- (void)testServicePointModalWhenTabChangedThenDisplaysCorrectContent7UMIWRPg9Zo3wq1YOhzFTests497 {
}

// integration_test/test/service_point_modal_test.dart
- (void)testServicePointModalWhenTimeoutThenClosesAutomaticallyL3iVFDwk1kZ8T4ZBo1cWTests497 {
}

// integration_test/test/service_point_modal_test.dart
- (void)testServicePointModalWhenAdvancementPausedThenClosesAfterTimeoutPzMRSkgLsqo1cXXDrSsfTests497 {
}

// integration_test/test/service_point_modal_test.dart
- (void)testGraduatedSpeedWhenPresentThenDisplaysInfoDetails4mjc7eeGUBicOSw69JyaTests231 {
}

// integration_test/test/service_point_modal_test.dart
- (void)testCommunicationTabWhenOpenedThenDisplaysNetworkAndRadioChannels02dNNCKAdwRRIPFdP8rGTests229 {
}

// integration_test/test/service_point_modal_test.dart
- (void)testCommunicationTabWhenOpenedFromOtherTabThenShowsInformationPNuI8yhc85razhMIsaEzTests229 {
}

// integration_test/test/service_point_modal_test.dart
- (void)testCommunicationTabWhenDepartureAuthorizationPresentThenDisplaysInModal02darOPX5OqoT03mCvB8Tests226 {
}

// integration_test/test/service_point_modal_test.dart
- (void)testLocalRegulationTabWhenPresentThenShowsTabG2KZy4GAFAAPIQmDGEFgTests95 {
}

// integration_test/test/service_point_modal_test.dart
- (void)testLocalRegulationTabWhenTabChangedThenUpdatesDisplayLoEWPFSo4Qcapw2AvhUzTests95 {
}

// integration_test/test/service_point_modal_test.dart
- (void)testLocalRegulationTabWhenOpenedThenShowsWebviewCCcUxowsksJLPQMqsXTTTests95 {
}

// integration_test/test/service_point_modal_test.dart
- (void)testServicePointModalWhenModalOpenThenShowsShortSignalNamesD56hz2flGTW6tj4oME9VTests980 {
}

// integration_test/test/service_point_modal_test.dart
- (void)testServicePointModalWhenNavigatedAndReturnedThenStaysDisplayed1qSvqp8jis2qsg4DKLiOTests497 {
}

// integration_test/test/settings_test.dart
- (void)testSettingsWhenDecisiveGradientDisabledThenHidesGradientsDnFjNfPHHPUOOjuVfnrETests583 {
}

// integration_test/test/settings_test.dart
- (void)testSettingsWhenKmHeaderClickedWithGradientHiddenThenTogglesDisplayLdW7fZGpdN3zYtjjtDUATests583 {
}

// integration_test/test/settings_test.dart
- (void)testSettingsWhenStationSignalHiddenThenHidesCorrectSignalsWfJtznpIEKWtPVmb9Rw0Tests811 {
}

// integration_test/test/settings_test.dart
- (void)testSettingsWhenStationSignalHiddenThenChevronPositionsCorrectly3XKYDX4SwTJLxyNqgMoiTests811 {
}

// integration_test/test/settings_test.dart
- (void)testSettingsWhenStationSignalsToggledThenHidesButKeepsEtcsStopSignsVxFGyvH5oEItemAd3evQTests16281484 {
}

// integration_test/test/settings_test.dart
- (void)testSettingsWhenEtcsConventionalToggledThenHidesOnlyConventionalStopSignD70x81OKbP7Mf1fPtJeJTests16281484 {
}

// integration_test/test/settings_test.dart
- (void)testSettingsWhenEtcsExtendedToggledThenHidesOnlyExtendedStopSignsWyFGcqFBAgRTeltqj00QTests16281484 {
}

// integration_test/test/settings_test.dart
- (void)testSettingsWhenBothEtcsToggledOffThenHidesAllEtcsStopSignsX7guyj0RrgJ3kyCghZapTests16281484 {
}

// integration_test/test/short_term_changes_test.dart
- (void)testShortTermChangesWhenPresentThenDisplaysAllCorrectlyInJourneyTableRpkZRlCOuFvVOdilaJ3HTests99 {
}

// integration_test/test/short_term_changes_test.dart
- (void)testShortTermChangesWhenPresentThenDisplaysAllCorrectlyInFlapKSHBUNCrkaLVbI9O4davTests99 {
}

// integration_test/test/suspicious_segment_test.dart
- (void)testSuspiciousSegmentWhenLoadedThenShowsRowsAndNotificationAndDismissesEHJMbX24ewGWgg10BEZqTests409 {
}

// integration_test/test/suspicious_segment_test.dart
- (void)testSuspiciousSegmentWhenAllPassedThenDisappearsAndReappearsOnUpdateOBl4K6VmunFHbxfUZby8Tests409 {
}

// integration_test/test/suspicious_segment_test.dart
- (void)testSuspiciousSegmentWhenJourneyUpdatedThenShowsNotificationCqASKmxsyq2yekUchh6yTests409 {
}

// integration_test/test/tour_system_link_test.dart
- (void)testTourSystemWhenNotConfiguredThenHidesButtonsJpXgUIrH7wxQNvb04ZMJTests96 {
}

// integration_test/test/tour_system_link_test.dart
- (void)testTourSystemWhenConfiguredThenShowsButtonsDNnl6Kr0CR51GHFbwop5Tests96 {
}

// integration_test/test/tour_system_link_test.dart
- (void)testTourSystemWhenPositionChangesThenUpdatesButtonVisibilityLSHbN4Urksjx7NapW9GOTests96 {
}

// integration_test/test/train_search_test.dart
- (void)testTrainSearchWhenPageLoadedThenShowsDefaultValuesYJsLvmX6PrhDbt3GNctgTests92 {
}

// integration_test/test/train_search_test.dart
- (void)testTrainSearchWhenCompanySelectionOpenedThenShowsOptions4V8lVLIAXkStk9lkHcFvTests92 {
}

// integration_test/test/train_search_test.dart
- (void)testTrainSearchWhenRuFilterEnteredThenFiltersResultsK9LxJibBfWA0sakjBxjUTests596 {
}

// integration_test/test/train_search_test.dart
- (void)testTrainSearchWhenNoTrainNumberEnteredThenDisablesButton3JEyvxxjnxVGfeAOufjKTests92 {
}

// integration_test/test/train_search_test.dart
- (void)testTrainSearchWhenYesterdaySelectedThenShowsWarningRh6SvdbhmUIBNyDfPXfOTests92 {
}

// integration_test/test/train_search_test.dart
- (void)testTrainSearchWhenDayBeforeYesterdayThenCannotSelectT4mNyzwoakPFwz6CYPkaTests92 {
}

// integration_test/test/train_search_test.dart
- (void)testTrainSearchWhenJpUnavailableThenShowsErrorIPmnmRoSSpBBs6aHadTkTests92 {
}

// integration_test/test/train_search_test.dart
- (void)testTrainSearchWhenErrorFromSferaThenDisplaysErrorCode9UIII436R7pMUXwLx6zRTests652 {
}

// integration_test/test/train_search_test.dart
- (void)testTrainSearchWhenMultipleCompanyMatchesThenShowsSelectionEdyQLmRIb617kcxR5XXNTests702703 {
}

// integration_test/test/train_search_test.dart
- (void)testTrainSearchWhenLastCompanyCodeRememberedThenAutoSelectsG6t83P9j45q6KfT4Y70fTests702 {
}

// integration_test/test/train_search_test.dart
- (void)testTrainSearchWhenNoCompanyMatchThenShowsNoResultMessageWQ4rTB8lZNGl5HW7Dbq0Tests702 {
}

// integration_test/test/warnapp_test.dart
- (void)testWarnappWhenSignalIsRedThenTriggersWarningFyC1jKH9cdcBV12PSb7qTests98 {
}

// integration_test/test/warnapp_test.dart
- (void)testWarnappWhenUiRebuiltThenNotificationNotReappearingUoTbX3SWk0ErQ5UKnyPQTests98 {
}

// integration_test/test/warnapp_test.dart
- (void)testWarnappWhenManeuverButtonTappedThenActivatesManeuverModeFzvOU1FQOyjnN2eS2nO0Tests98 {
}

// integration_test/test/warnapp_test.dart
- (void)testWarnappWhenInManeuverModeThenDoesNotTriggerL1acZ9QnjvNYwfLsKH9YTests98 {
}

// integration_test/test/warnapp_test.dart
- (void)testWarnappWhenSignalIsGreenThenDoesNotTrigger8eVsobX4adhhZeX7htwvTests98 {
}
// END GENERATED XCTESTS

@end
