@import XCTest;
@import integration_test;
@import ObjectiveC.runtime;
@import UIKit;

// Generated by app/scripts/generate_runner_tests.js.
//
// This file creates one XCTest case per Flutter integration test found under
// app/integration_test/test. The Flutter test suite is executed lazily once and
// stores successful test selector names in RunnerSuccessfulTests.
// Each generated XCTest validates that its selector name appears in that list.
//
// The original motivation is to avoid the Xcode 15+ construction watchdog while
// still exposing individual XCTest results instead of a single aggregate test.
static NSMutableArray<NSString *> *RunnerTestFailures;
static NSMutableSet<NSString *> *RunnerSuccessfulTests;
static NSDictionary<NSString *, UIImage *> *RunnerCapturedScreenshotsByName;
static BOOL RunnerIntegrationTestsDidRun = NO;
static BOOL RunnerScreenshotsAttached = NO;

@interface RunnerTests : XCTestCase
+ (NSArray<NSString *> *)recordedFailures;
+ (NSArray<NSString *> *)recordedSuccessfulTests;
@end

@implementation RunnerTests

+ (NSArray<NSString *> *)recordedFailures {
  return RunnerTestFailures.copy ?: @[];
}

+ (NSArray<NSString *> *)recordedSuccessfulTests {
  return RunnerSuccessfulTests.allObjects ?: @[];
}

- (void)ensureIntegrationTestsExecuted {
  @synchronized([RunnerTests class]) {
    if (RunnerIntegrationTestsDidRun) {
      [self attachCapturedScreenshotsIfNeeded];
      return;
    }

    RunnerIntegrationTestsDidRun = YES;
    RunnerTestFailures = [[NSMutableArray alloc] init];
    RunnerSuccessfulTests = [[NSMutableSet alloc] init];

    FLTIntegrationTestRunner *integrationTestRunner = [[FLTIntegrationTestRunner alloc] init];
    [integrationTestRunner testIntegrationTestWithResults:^(SEL testSelector, BOOL success, NSString *failureMessage) {
      NSString *name = NSStringFromSelector(testSelector);
      if (success) {
        [RunnerSuccessfulTests addObject:name];
      } else {
        [RunnerTestFailures addObject:[NSString stringWithFormat:@"%@: %@", name, failureMessage ?: @"(no message)"]];
      }
    }];

    RunnerCapturedScreenshotsByName = integrationTestRunner.capturedScreenshotsByName ?: @{};
  }

  [self attachCapturedScreenshotsIfNeeded];
}

- (void)attachCapturedScreenshotsIfNeeded {
  @synchronized([RunnerTests class]) {
    if (RunnerScreenshotsAttached) {
      return;
    }

    RunnerScreenshotsAttached = YES;
    [RunnerCapturedScreenshotsByName enumerateKeysAndObjectsUsingBlock:^(NSString *name, UIImage *screenshot, BOOL *stop) {
      XCTAttachment *attachment = [XCTAttachment attachmentWithImage:screenshot];
      attachment.lifetime = XCTAttachmentLifetimeKeepAlways;
      if (name != nil) {
        attachment.name = name;
      }
      [self addAttachment:attachment];
    }];
  }
}

- (NSString *)recordedFailureWithPrefix:(NSString *)testNamePrefix {
  [self ensureIntegrationTestsExecuted];

  NSString *expectedPrefix = [NSString stringWithFormat:@"%@:", testNamePrefix];
  for (NSString *failure in RunnerTestFailures ?: @[]) {
    if ([failure hasPrefix:expectedPrefix]) {
      return failure;
    }
  }

  return nil;
}

- (BOOL)hasRecordedSuccessWithPrefix:(NSString *)testNamePrefix {
  [self ensureIntegrationTestsExecuted];

  for (NSString *successfulTestName in RunnerSuccessfulTests ?: [NSSet set]) {
    if ([successfulTestName hasPrefix:testNamePrefix]) {
      return YES;
    }
  }

  return NO;
}

- (void)assertRecordedSuccessWithPrefix:(NSString *)testNamePrefix {
  if ([self hasRecordedSuccessWithPrefix:testNamePrefix]) {
    return;
  }

  NSString *failure = [self recordedFailureWithPrefix:testNamePrefix];
  if (failure != nil) {
    XCTFail(@"%@", failure);
    return;
  }

  NSArray<NSString *> *successfulTests = [[RunnerSuccessfulTests allObjects] sortedArrayUsingSelector:@selector(compare:)];
  XCTFail(@"Expected %@ in successful tests list, but it was not recorded. Successful tests:\n%@",
          testNamePrefix,
          [successfulTests componentsJoinedByString:@"\n"]);
}

// BEGIN GENERATED XCTESTS
// integration_test/test/manual_advancement_test.dart
- (void)testManualAdvancementTestsManualAdvancementWhenServicePointDraggedThenJourneyPositionMoved {
  [self assertRecordedSuccessWithPrefix:@"testManualAdvancementTestsManualAdvancementWhenServicePointDraggedThenJourneyPositionMoved"];
}

// integration_test/test/manual_advancement_test.dart
- (void)testManualAdvancementTestsManualAdvancementWhenManualPositionSetThenManualModeActivatedUntilJourneyPositionSignaled {
  [self assertRecordedSuccessWithPrefix:@"testManualAdvancementTestsManualAdvancementWhenManualPositionSetThenManualModeActivatedUntilJourneyPositionSignaled"];
}

// integration_test/test/manual_advancement_test.dart
- (void)testManualAdvancementTestsManualAdvancementWhenManualPositionSetThenStartTimedAdvancement {
  [self assertRecordedSuccessWithPrefix:@"testManualAdvancementTestsManualAdvancementWhenManualPositionSetThenStartTimedAdvancement"];
}
// END GENERATED XCTESTS

@end
