package ch.sbb.backend.common;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.media.Schema.RequiredMode;
import java.net.URI;
import lombok.Builder;
import lombok.Builder.Default;
import lombok.NonNull;
import lombok.Value;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;

/**
 * Machine readable error response.
 * <p>
 * AITG-1599
 *
 * @see <a href="https://datatracker.ietf.org/doc/html/rfc9457">RFC 9457 Problem Details for HTTP APIs</a>
 * @see <a href="https://schweizerischebundesbahnen.github.io/api-principles/restful/best-practices/#use-problem-json>SBB API Principles, RESTful Best Practice</a>
 * @see <a href="https://opensource.zalando.com/restful-api-guidelines/#176">MUST use problem JSON [176]</a>
 * @see <a href="https://opensource.zalando.com/problem/schema.yaml">Problem opensource schema</a>
 * @see <a href="https://opensource.zalando.com/restful-api-guidelines/#234">MUST only use durable and immutable remote references [234]</a>
 * @see <a href="https://opensource.zalando.com/restful-api-guidelines/#151">MUST specify success and error responses [151]</a>
 * @see org.springframework.http.ProblemDetail compatibility
 */
@Schema(description = "Zalando like error-object if not HttpStatus 2xx (see " + ApiDocumentation.RFC9457 + "). Check for: " + HttpHeaders.CONTENT_TYPE + "="
    + MediaType.APPLICATION_PROBLEM_JSON_VALUE)
@Builder
@Value
@JsonPropertyOrder({"status", "title", "detail", "instance", "type"})
public class Problem implements Response {

    @Schema(description = "The HTTP status code generated by the origin server for this occurrence of the problem.",
        requiredMode = RequiredMode.REQUIRED,
        minimum = "100", maximum = "600", exclusiveMaximum = true,
        example = "500")
    @NonNull
    Integer status;

    @Schema(description = "A short, human-readable summary of the problem type.",
        requiredMode = RequiredMode.NOT_REQUIRED /* not always given, like Spring errors */,
        example = "Service Unavailable")
    String title;

    @Schema(description = "A human readable explanation specific to this occurrence of the problem.",
        requiredMode = RequiredMode.NOT_REQUIRED /* not always given, like Spring errors */)
    String detail;

    // absolute URIs RECOMMENDED
    @Schema(description = "An URI that identifies the specific occurrence of the problem. It corresponds to the called endpoint but does not identify uniquely a call. ",
        requiredMode = RequiredMode.NOT_REQUIRED, example = "/v1/settings")
    URI instance;

    /**
     * Variants acc. to RFC 9475:
     * <ul>
     *     <li>resolvable type URIs are encouraged by this specification (if locator (like "https" scheme), dereferencing it SHOULD provide human-readable documentation for the problem type</li>
     *     <li>relative URI</li>
     *     <li>non resolvable URI for e.g. "tag:example@example.org,2021-09-17:OutOfLuck"</li>
     * </ul>
     */
    @Schema(description = "An absolute URI that identifies the problem type. When dereferenced, it will provide human-readable documentation for devOps engineers." +
        " If empty refer to [general `Problem` documentation]("+ApiDocumentation.PROBLEM_TYPE+").",
        requiredMode = RequiredMode.NOT_REQUIRED)
    URI type;
}
