include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120
  trailing_commas: preserve

linter:
  rules:
    always_use_package_imports: true
    prefer_single_quotes: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_final_fields: true
    always_put_required_named_parameters_first: true

analyzer:
  exclude:
    - '**.mocks.dart'
    - '**.fake.dart'
    - '**.g.dart'
    - '**.gr.dart'
