include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120

linter:
  rules:
    always_use_package_imports: true
    prefer_single_quotes: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_final_fields: true
    always_put_required_named_parameters_first: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
analyzer:
  plugins:
    - custom_lint
  exclude:
    - lib/**.g.dart
    - test/**.mocks.dart
