@startuml components

component app
component auth
component logger
component formation
component sfera
component mqtt
component connectivity_x
component local_regulations
component settings
component warnapp
component mqtt_client #4DB1FF
component http_x
component http #4DB1FF
component connectivity_plus #4DB1FF
component app_links #4DB1FF
component app_links_x
component preload

app --> auth
app --> sfera
app --> mqtt
app --> connectivity_x
app --> local_regulations
app --> settings
app --> warnapp
app --> logger
app --> http_x
app --> formation
app --> app_links
app --> preload

settings --> http_x
settings --> logger

formation --> http_x

logger --> http_x

sfera --> mqtt
sfera --> http_x

local_regulations --> sfera

http_x *-- http

mqtt --> connectivity_x
mqtt *-- mqtt_client

connectivity_x *-- connectivity_plus

app_links_x *-- app_links

preload --> settings
preload --> sfera

@enduml