name: das_client
publish_to: none
description: "DAS (Driver Advisory System) is a mobile application that provides all the required journey data to the train driver."

environment:
  sdk: ^3.11.3

workspace:
  - "*"

dependencies:
  logging: ^1.3.0

dev_dependencies:
  # https://pub.dev/packages/melos
  melos: ^7.5.1

# Melos Configuration
melos:
  scripts:
    clean:das:
      description: Run cleanup of das client files
      run: flutter clean
      exec:
        concurrency: 4
      packageFilters:
        flutter: true

    generate:
      steps:
        - melos run generate:build_runner --no-select
        - melos run generate:intl

    generate:build_runner:
      run: dart run build_runner build --delete-conflicting-outputs
      description: Run build_runner in all components
      exec:
        orderDependents: true
      packageFilters:
        dependsOn: "build_runner"

    generate:intl:
      run: flutter gen-l10n
      description: Run generation of internationalization files
      exec:
        concurrency: 1
      packageFilters:
        dirExists: l10n

    test:
      run: flutter test --no-pub
      description: Run tests in components with test dir
      exec:
        failFast: false
      packageFilters:
        dirExists: test

    coverage:
      run: flutter test --coverage --no-pub
      description: Run tests with coverage in components with test dir
      exec:
        failFast: false
      packageFilters:
        dirExists: test

    unused_code:
      run: dart run flutter_prunekit unused_code
      description: Run build_runner in all components
      exec:
        failFast: false
      packageFilters:
        dependsOn: "flutter_prunekit"

  command:
    clean:
      hooks:
        post: melos run clean:das --no-select