package ch.sbb.backend.formation.domain.model;

/**
 * Part of the generated POJOs of ZIS by schema registry.
 * todo: should be generated by the schema registry
 */
public enum BrakeDesign {
    NORMALE_BREMSAUSRUESTUNG_KEINE_MERKMALE(0),
    SCHEIBENBREMSEN(1),
    KUNSTSTOFF_BREMSKLOETZE(2),
    EINLOESIGE_BREMSE(3),
    EINLOESIGE_BREMSE_MIT_KUNSTSTOFF_BREMSKLOETZEN(4),
    L_KUNSTSTOFF_LEISE(5),
    LL_KUNSTSTOFF_LEISE_LEISE(6),
    NICHT_KODIERT(9);

    private final int key;

    BrakeDesign(int key) {
        this.key = key;
    }

    public static BrakeDesign valueOfKey(int key) {
        for (BrakeDesign brakeDesign : BrakeDesign.values()) {
            if (brakeDesign.key == key) {
                return brakeDesign;
            }
        }
        throw new IllegalArgumentException("No BrakeDesign with key: " + key);
    }
}