package ch.sbb.backend.formation.domain.model;

/**
 * Part of the generated POJOs of ZIS by schema registry.
 * todo: should be generated by the schema registry
 */
public enum VehicleCategory {
    LOKOMOTIVE, TRIEBWAGEN, STEUERWAGEN, GUETERWAGEN, PERSONENWAGEN, GLIEDERFAHRZEUG, ANHAENGELAST
}
