/*
 * API model.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.30.6-SNAPSHOT
 * Contact: journey@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package _todo_;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * Zalando like error-object if not HttpStatus 2xx (see [RFC-7807](https://tools.ietf.org/html/rfc7807)). Check for: Content-Type&#x3D;application/problem+json
 *
 * @deprecated TODO https://github.com/SchweizerischeBundesbahnen/DAS/issues/1430 declare as model in das_backend to be auto-generated (correlates to das_backend/../ApiErrorResponses)
 */
@Deprecated
@JsonPropertyOrder({
    Problem.JSON_PROPERTY_STATUS,
    Problem.JSON_PROPERTY_CODE,
    Problem.JSON_PROPERTY_TYPE,
    Problem.JSON_PROPERTY_TITLE,
    Problem.JSON_PROPERTY_DETAIL,
    Problem.JSON_PROPERTY_INSTANCE,
    Problem.JSON_PROPERTY_TRACE_ID,
    Problem.JSON_PROPERTY_DOCUMENTATION,
    Problem.JSON_PROPERTY_TRANSLATION_KEY,
    Problem.JSON_PROPERTY_DISPLAY_TITLE,
    Problem.JSON_PROPERTY_DISPLAY_DETAIL,
    Problem.JSON_PROPERTY_DISPLAY_RESOLUTION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-07T08:07:28.686185200+01:00[Europe/Zurich]")
public class Problem {

    public static final String JSON_PROPERTY_STATUS = "status";
    private Integer status;

    public static final String JSON_PROPERTY_CODE = "code";
    private String code;

    public static final String JSON_PROPERTY_TYPE = "type";
    private String type;

    public static final String JSON_PROPERTY_TITLE = "title";
    private String title;

    public static final String JSON_PROPERTY_DETAIL = "detail";
    private String detail;

    public static final String JSON_PROPERTY_INSTANCE = "instance";
    private String instance;

    public static final String JSON_PROPERTY_TRACE_ID = "traceId";
    private String traceId;

    public static final String JSON_PROPERTY_DOCUMENTATION = "documentation";
    private String documentation = "https://github.com/SchweizerischeBundesbahnen/journey-service/blob/master/Problem-Manual.md";

    public static final String JSON_PROPERTY_TRANSLATION_KEY = "translationKey";
    private String translationKey;

    public static final String JSON_PROPERTY_DISPLAY_TITLE = "displayTitle";
    private String displayTitle;

    public static final String JSON_PROPERTY_DISPLAY_DETAIL = "displayDetail";
    private String displayDetail;

    public static final String JSON_PROPERTY_DISPLAY_RESOLUTION = "displayResolution";
    private String displayResolution;

    public Problem() {
    }

    public Problem status(Integer status) {

        this.status = status;
        return this;
    }

    /**
     * The HTTP status code generated by the origin server for this occurrence of the problem. minimum: 100 maximum: 600
     *
     * @return status
     **/
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_STATUS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public Integer getStatus() {
        return status;
    }

    @JsonProperty(JSON_PROPERTY_STATUS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setStatus(Integer status) {
        this.status = status;
    }

    public Problem code(String code) {

        this.code = code;
        return this;
    }

    /**
     * A code that identifies the specific occurrence of the problem. It corresponds to the part after the prefix of the &#x60;type&#x60; URI.
     *
     * @return code
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getCode() {
        return code;
    }

    @JsonProperty(JSON_PROPERTY_CODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCode(String code) {
        this.code = code;
    }

    public Problem type(String type) {

        this.type = type;
        return this;
    }

    /**
     * An absolute URI that identifies the problem type. When dereferenced, it will NOT provide human-readable documentation, for that see &#x60;documentation&#x60;.
     *
     * @return type
     **/
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getType() {
        return type;
    }

    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setType(String type) {
        this.type = type;
    }

    public Problem title(String title) {

        this.title = title;
        return this;
    }

    /**
     * A short, human-readable summary of the problem type. Written in english and readable for engineers (usually not suited for non technical stakeholders and not localized).
     *
     * @return title
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TITLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getTitle() {
        return title;
    }

    @JsonProperty(JSON_PROPERTY_TITLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTitle(String title) {
        this.title = title;
    }

    public Problem detail(String detail) {

        this.detail = detail;
        return this;
    }

    /**
     * A human readable explanation specific to this occurrence of the problem and readable for engineers (usually not suited for non technical stakeholders and not localized).
     *
     * @return detail
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DETAIL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDetail() {
        return detail;
    }

    @JsonProperty(JSON_PROPERTY_DETAIL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDetail(String detail) {
        this.detail = detail;
    }

    public Problem instance(String instance) {

        this.instance = instance;
        return this;
    }

    /**
     * An absolute URI that identifies the specific occurrence of the problem. It corresponds to the called endpoint but does not identify uniquely a call (for that, use the &#x60;traceId&#x60;).
     *
     * @return instance
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_INSTANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getInstance() {
        return instance;
    }

    @JsonProperty(JSON_PROPERTY_INSTANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setInstance(String instance) {
        this.instance = instance;
    }

    public Problem traceId(String traceId) {

        this.traceId = traceId;
        return this;
    }

    /**
     * The &#x60;trace-id&#x60; according to the [W3C tracing standard](https://www.w3.org/TR/trace-context/#traceparent-header). Give it back when asking support by the operating team.)
     *
     * @return traceId
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TRACE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getTraceId() {
        return traceId;
    }

    @JsonProperty(JSON_PROPERTY_TRACE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTraceId(String traceId) {
        this.traceId = traceId;
    }

    public Problem documentation(String documentation) {

        this.documentation = documentation;
        return this;
    }

    /**
     * An absolute URI that point to the documentation. When dereferenced, it SHOULD provide human-readable documentation for the problem type (e.g., using HTML).
     *
     * @return documentation
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DOCUMENTATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDocumentation() {
        return documentation;
    }

    @JsonProperty(JSON_PROPERTY_DOCUMENTATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDocumentation(String documentation) {
        this.documentation = documentation;
    }

    public Problem translationKey(String translationKey) {

        this.translationKey = translationKey;
        return this;
    }

    /**
     * The translation key resolving the &#x60;displayTitle&#x60; and other displayable information, usefull to translate in non-SBB languages.
     *
     * @return translationKey
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TRANSLATION_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getTranslationKey() {
        return translationKey;
    }

    @JsonProperty(JSON_PROPERTY_TRANSLATION_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTranslationKey(String translationKey) {
        this.translationKey = translationKey;
    }

    public Problem displayTitle(String displayTitle) {

        this.displayTitle = displayTitle;
        return this;
    }

    /**
     * The title of the problem for the end-user, translated. Use it together with &#x60;displayDetail&#x60; and &#x60;displayResolution&#x60;.
     *
     * @return displayTitle
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DISPLAY_TITLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDisplayTitle() {
        return displayTitle;
    }

    @JsonProperty(JSON_PROPERTY_DISPLAY_TITLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDisplayTitle(String displayTitle) {
        this.displayTitle = displayTitle;
    }

    public Problem displayDetail(String displayDetail) {

        this.displayDetail = displayDetail;
        return this;
    }

    /**
     * The message of the problem for the end-user, translated. Use it together with &#x60;displayTitle&#x60; and &#x60;displayResolution&#x60;.
     *
     * @return displayDetail
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DISPLAY_DETAIL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDisplayDetail() {
        return displayDetail;
    }

    @JsonProperty(JSON_PROPERTY_DISPLAY_DETAIL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDisplayDetail(String displayDetail) {
        this.displayDetail = displayDetail;
    }

    public Problem displayResolution(String displayResolution) {

        this.displayResolution = displayResolution;
        return this;
    }

    /**
     * The proposition for resolution of the problem for the end-user, translated. Use it together with &#x60;displayTitle&#x60; and &#x60;displayDetail&#x60;.
     *
     * @return displayResolution
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DISPLAY_RESOLUTION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDisplayResolution() {
        return displayResolution;
    }

    @JsonProperty(JSON_PROPERTY_DISPLAY_RESOLUTION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDisplayResolution(String displayResolution) {
        this.displayResolution = displayResolution;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Problem problem = (Problem) o;
        return Objects.equals(this.status, problem.status) &&
            Objects.equals(this.code, problem.code) &&
            Objects.equals(this.type, problem.type) &&
            Objects.equals(this.title, problem.title) &&
            Objects.equals(this.detail, problem.detail) &&
            Objects.equals(this.instance, problem.instance) &&
            Objects.equals(this.traceId, problem.traceId) &&
            Objects.equals(this.documentation, problem.documentation) &&
            Objects.equals(this.translationKey, problem.translationKey) &&
            Objects.equals(this.displayTitle, problem.displayTitle) &&
            Objects.equals(this.displayDetail, problem.displayDetail) &&
            Objects.equals(this.displayResolution, problem.displayResolution);
    }

    @Override
    public int hashCode() {
        return Objects.hash(status, code, type, title, detail, instance, traceId, documentation, translationKey, displayTitle, displayDetail, displayResolution);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Problem {\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    code: ").append(toIndentedString(code)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
        sb.append("    instance: ").append(toIndentedString(instance)).append("\n");
        sb.append("    traceId: ").append(toIndentedString(traceId)).append("\n");
        sb.append("    documentation: ").append(toIndentedString(documentation)).append("\n");
        sb.append("    translationKey: ").append(toIndentedString(translationKey)).append("\n");
        sb.append("    displayTitle: ").append(toIndentedString(displayTitle)).append("\n");
        sb.append("    displayDetail: ").append(toIndentedString(displayDetail)).append("\n");
        sb.append("    displayResolution: ").append(toIndentedString(displayResolution)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

