
on:
  push:
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'
    branches: [ "main" ]

jobs:
  check-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint workflows using actionlint # https://github.com/rhysd/actionlint/tree/main
        uses: raven-actions/actionlint@v2