
on:
  pull_request:
    paths:
      - '.github/workflows/**'
    branches: [ "main" ]

jobs:
  check-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Lint workflows using actionlint # https://github.com/rhysd/actionlint/tree/main
        uses: raven-actions/actionlint@3d39aea434753780c3b3d4a1a31c854b4dbf49d7 # v2.2.0