name: Continuous Integration Webapp

defaults:
  run:
    working-directory: webapp

on:
  push:
    paths:
      - 'webapp/**'
  pull_request:
    paths:
      - 'webapp/**'


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'webapp/.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'webapp/package-lock.json'
      - run: npm clean-install
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'webapp/.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'webapp/package-lock.json'
      - run: npm clean-install
      - run: npm test

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'webapp/.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'webapp/package-lock.json'
      - run: npm clean-install
      - run: npm run build
      - name: Store build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/webapp/
