name: Continuous Integration Webapp

defaults:
  run:
    working-directory: das_playground

on:
  push:
    paths:
      - 'das_playground/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'das_playground/**'
    branches: [ "main" ]


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: bashCmd
        shell: bash
        run: |
          echo "GH_REPO: $GH_REPO"
          echo "CI Webapp"