name: Client Browserstack E2E

on:
  schedule:
    - cron: '34 3 * * *'
  workflow_dispatch:

jobs:
  browserstack:
    uses: ./.github/workflows/client_browserstack_base.yml
    with:
      entrypoint: integration_test/app_e2e_test.dart
      enable_e2e: true
    secrets: inherit
