# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Build Test Analyze

defaults:
  run:
    working-directory: das_client

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - 'das_client/**'
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'
        cache: true

    - name: Get dependencies
      run: flutter pub get

    - name: Format check with line length 120
      run: dart format -l 120 -o none --set-exit-if-changed .

    - name: Src generation
      run: dart run build_runner build --delete-conflicting-outputs

    - name: Generate localization files
      run:  flutter gen-l10n

    - name: Flutter analyze
      run: flutter analyze

    - name: Custom linter
      run: flutter pub run custom_lint --no-fatal-infos

    - name: Flutter test
      run: flutter test

