# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter iOS Build

defaults:
  run:
    working-directory: das_client
    
on:
  push:
    paths:
      - 'das_client/**'
    branches: [ "feature/ios-signing" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'
    - name: Install the Apple certificate and provisioning profile
      env:
        APPSTORE_CONNECT_PRIVATE_KEY_BASE64: ${{ secrets.APPSTORE_CONNECT_PRIVATE_KEY_BASE64 }}
        APPSTORE_CONNECT_KEY_ID: ${{ secrets.APPSTORE_CONNECT_KEY_ID }}
      run: |
        # create variables
        APPSTORE_CONNECT_PRIVATE_KEY_PATH=~/PrivateKeys/AuthKey_$APPSTORE_CONNECT_KEY_ID.p8

        # import certificate and provisioning profile from secrets
        echo -n "$APPSTORE_CONNECT_PRIVATE_KEY_BASE64" | base64 --decode -o $APPSTORE_CONNECT_PRIVATE_KEY_PATH
    - run: |
        flutter pub get
        flutter pub run build_runner build --delete-conflicting-outputs
    - run: flutter test
    - name: Build and Deploy iOS App
      env:
        APPSTORE_CONNECT_KEY_ID: ${{ secrets.APPSTORE_CONNECT_KEY_ID }}
        APPSTORE_CONNECT_ISSUER_ID: ${{ secrets.APPSTORE_CONNECT_ISSUER_ID }}
      run: |
        flutter build ipa --flavor inte -t lib/main_inte.dart --release --no-codesign
        xcodebuild -exportArchive -archivePath "build/ios/archive/DAS Inte.xcarchive" -exportOptionsPlist ios/exportOptionsRelease.plist -allowProvisioningUpdates -authenticationKeyIssuerID $APPSTORE_CONNECT_ISSUER_ID -authenticationKeyID $APPSTORE_CONNECT_KEY_ID -authenticationKeyPath ~/PrivateKeys/AuthKey_$APPSTORE_CONNECT_KEY_ID.p8
#    - run: flutter build ios --flavor dev -t lib/main_dev.dart --release
#    - run: flutter build ios --flavor dev -t lib/main_dev.dart --release
#    - run: flutter build ios --flavor inte -t lib/main_inte.dart --release
#    - run: flutter build ios --flavor prod -t lib/main_prod.dart --release


