# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Build

defaults:
  run:
    working-directory: das_client
    
on:
  push:
    paths:
      - 'das_client/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'das_client/**'
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.2'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
    - run: flutter build appbundle
    - run: flutter build ios --release --no-codesign
