name: Issues flow

on:
  issues:
    types: [opened]

jobs:
  checkboxes:
    runs-on: ubuntu-latest
    steps:
      - name: Status backlog
        uses: actions/github-script@v7
        id: check_backlog
        with:
          script: |
            const labels = context.payload.issue.labels.map(label => label.name);
            return labels.includes('backlog');

      - name: Add checkboxes
#        if: steps.check_backlog.outputs.result == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const newBody = context.payload.issue.body + `
            - [ ] Task 1
            - [ ] Task 2
            - [ ] Task 3
            `;
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: newBody
            });
