name: Issues flow

on:
  issues:
    types: [opened, edited]

jobs:
  checkboxes:
    runs-on: ubuntu-latest
    steps:
      - name: Status
        uses: actions/github-script@v7
        id: status
        with:
          script: |
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            console.log(issue);
            return status

      - name: Add checkboxes
        if: github.event.action == 'opened'
        #        if: steps.check_backlog.outputs.result == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const newBody = context.payload.issue.body + `
            ## Tasks:
            - [ ] BA
            - [ ] UX
            
            Wenn alle Tasks abgeschlossen geht die Story in den Status `Entwicklungsteam Review`
            `;
            
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: newBody
            });
