name: PR Title Linter
on:
  pull_request:
    types: [opened, edited, reopened, unlocked, synchronize]

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
      - name: Install commitlint
        run: |
          npm install @commitlint/config-conventional
          npm install commitlint@latest
          echo "module.exports = { extends: ['@commitlint/config-conventional'], rules: { 'issue-references': [2, 'always'] }, plugins: [{ rules: { 'issue-references': ({type, references}) => [!(type === 'feat' && references.length === 0), 'Feature must contain issue references'] } } ] };" > commitlint.config.js
      - name: "Lint: Pull request title"
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo $PR_TITLE | npx commitlint

      - name: "Warning: Pull request title must match patterns defined in CONTRIBUTING.md in section Commit Message Guidelines!"
        if: ${{ failure() }}
        run: echo "Pull request title must match patterns defined in CONTRIBUTING.md in section Commit Message Guidelines!"
