name: PR Title Linter
on:
  push:
    branches: [ "sfera-playground" ]
#on:
#  pull_request:
#    types: [opened, edited, reopened, unlocked]

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest

      - name: "Lint: Pull request title"
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo "$PR_TITLE" | npx commitlint

      - name: "Warning: Pull request title must match patterns defined in CONTRIBUTING.md in section Commit Message Guidelines!"
        if: ${{ failure() }}
        run: echo "Pull request title must match patterns defined in CONTRIBUTING.md in section Commit Message Guidelines!"
