on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'das_client-v*' # Push events to matching v*, i.e. v1.0, v20.15.10

defaults:
  run:
    working-directory: das_client

name: Build and Upload Release

jobs:
  build:
    name: Build and Upload Release
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build appbundle
      - run: flutter build ios --release --no-codesign
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/bundle/release/*.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
