# This workflow is triggered whenever a release please PR is merged with label autorelease:das_client.
# This builds and releases the iOS version of the app.

name: release-das-client-ios

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  prepare:
    if: (github.event.pull_request.merged && contains( github.event.pull_request.labels.*.name, 'release:das_client'))
    runs-on: macos-latest
    concurrency:
      group: release-das-client-ios
    defaults:
      run:
        working-directory: das_client

    steps:
      - uses: actions/checkout@v4

      - run: echo "Created DAS iOS CLient release"
